// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class ChatMessageFactory
	{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoChatMessageConstructDefaultNative();
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoChatMessageDestructNative(IntPtr obj);
		public static ChatMessage Create()
		{
			IntPtr objPtr = VidyoChatMessageConstructDefaultNative();
			return new ChatMessage(objPtr);
		}
		public static void Destroy(ChatMessage obj)
		{
			VidyoChatMessageDestructNative(obj.GetObjectPtr());
		}
	}
	public class ChatMessage{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoChatMessage reference.
		public IntPtr GetObjectPtr(){
			IntPtr nBody = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(body ?? string.Empty);
			IntPtr nUserId = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(userId ?? string.Empty);

			VidyoChatMessageSetbodyNative(objPtr, nBody);
			VidyoChatMessageSetidNative(objPtr, id);
			VidyoChatMessageSetsenderTypeNative(objPtr, senderType);
			VidyoChatMessageSettimestampNative(objPtr, timestamp);
			VidyoChatMessageSettypeNative(objPtr, type);
			VidyoChatMessageSetuserIdNative(objPtr, nUserId);

			Marshal.FreeHGlobal(nUserId);
			Marshal.FreeHGlobal(nBody);
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoChatMessageGetbodyNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoChatMessageSetbodyNative(IntPtr obj, IntPtr body);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern long VidyoChatMessageGetidNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoChatMessageSetidNative(IntPtr obj, long id);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern ChatMessageSenderType VidyoChatMessageGetsenderTypeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern void VidyoChatMessageSetsenderTypeNative(IntPtr obj, ChatMessageSenderType senderType);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoChatMessageGettimestampNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoChatMessageSettimestampNative(IntPtr obj, ulong timestamp);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern ChatMessageType VidyoChatMessageGettypeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern void VidyoChatMessageSettypeNative(IntPtr obj, ChatMessageType type);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoChatMessageGetuserIdNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoChatMessageSetuserIdNative(IntPtr obj, IntPtr userId);

		public enum ChatMessageSenderType{
			ChatmessagesendertypeUser,
			ChatmessagesendertypeRoom,
			ChatmessagesendertypeSystem,
			ChatmessagesendertypeNone
		}
		public enum ChatMessageType{
			ChatmessagetypeChat,
			ChatmessagetypeMediaStart,
			ChatmessagetypeMediaStop,
			ChatmessagetypePrivateChat
		}
		public enum ChatMessageTypingIndication{
			ChatmessagetypingindicationActive,
			ChatmessagetypingindicationComposing,
			ChatmessagetypingindicationGone,
			ChatmessagetypingindicationInactive,
			ChatmessagetypingindicationPaused,
			ChatmessagetypingindicationNone
		}
		public String body;
		public long id;
		public ChatMessageSenderType senderType;
		public ulong timestamp;
		public ChatMessageType type;
		public String userId;
		public ChatMessage(IntPtr obj){
			objPtr = obj;

			body = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoChatMessageGetbodyNative(objPtr));
			id = VidyoChatMessageGetidNative(objPtr);
			senderType = VidyoChatMessageGetsenderTypeNative(objPtr);
			timestamp = VidyoChatMessageGettimestampNative(objPtr);
			type = VidyoChatMessageGettypeNative(objPtr);
			userId = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoChatMessageGetuserIdNative(objPtr));
		}
	};
}
