// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class ContactFactory
	{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoContactConstructDefaultNative();
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoContactDestructNative(IntPtr obj);
		public static Contact Create()
		{
			IntPtr objPtr = VidyoContactConstructDefaultNative();
			return new Contact(objPtr);
		}
		public static void Destroy(Contact obj)
		{
			VidyoContactDestructNative(obj.GetObjectPtr());
		}
	}
	public class Contact{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoContact reference.
		public IntPtr GetObjectPtr(){
			IntPtr nDepartment = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(department ?? string.Empty);
			IntPtr nEmails = Marshal.AllocHGlobal(Marshal.SizeOf<IntPtr>() * emails.Count);
			int nEmailsSize = 0;
			IntPtr nGroups = Marshal.AllocHGlobal(Marshal.SizeOf<IntPtr>() * groups.Count);
			int nGroupsSize = 0;
			IntPtr nHandle = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(handle ?? string.Empty);
			IntPtr nId = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(id ?? string.Empty);
			IntPtr nName = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(name ?? string.Empty);
			IntPtr nNickname = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(nickname ?? string.Empty);
			IntPtr nPhoto = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(photo ?? string.Empty);
			IntPtr nPresenceStatus = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(presenceStatus ?? string.Empty);
			IntPtr nTelephones = Marshal.AllocHGlobal(Marshal.SizeOf<IntPtr>() * telephones.Count);
			int nTelephonesSize = 0;
			IntPtr nTitle = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(title ?? string.Empty);

			foreach (ContactProperty iter in emails) {
				Marshal.WriteIntPtr(nEmails + (nEmailsSize * Marshal.SizeOf<IntPtr>()), iter.GetObjectPtr());
				nEmailsSize++;
			}
			foreach (String iter in groups) {
				Marshal.WriteIntPtr(nGroups + (nGroupsSize * Marshal.SizeOf<IntPtr>()), MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(iter ?? string.Empty));
				nGroupsSize++;
			}
			foreach (ContactProperty iter in telephones) {
				Marshal.WriteIntPtr(nTelephones + (nTelephonesSize * Marshal.SizeOf<IntPtr>()), iter.GetObjectPtr());
				nTelephonesSize++;
			}

			VidyoContactSetdepartmentNative(objPtr, nDepartment);
			VidyoContactSetemailsNative(objPtr, nEmails, nEmailsSize);
			VidyoContactSetgroupsNative(objPtr, nGroups, nGroupsSize);
			VidyoContactSethandleNative(objPtr, nHandle);
			VidyoContactSetidNative(objPtr, nId);
			VidyoContactSetnameNative(objPtr, nName);
			VidyoContactSetnicknameNative(objPtr, nNickname);
			VidyoContactSetphotoNative(objPtr, nPhoto);
			VidyoContactSetpresenceStateNative(objPtr, presenceState);
			VidyoContactSetpresenceStatusNative(objPtr, nPresenceStatus);
			VidyoContactSetpublicationStateNative(objPtr, publicationState);
			VidyoContactSetsubscriptionStateNative(objPtr, subscriptionState);
			VidyoContactSettelephonesNative(objPtr, nTelephones, nTelephonesSize);
			VidyoContactSettimestampNative(objPtr, timestamp);
			VidyoContactSettitleNative(objPtr, nTitle);

			for (int i = 0; i < nGroupsSize; i++) {
				Marshal.FreeHGlobal(Marshal.ReadIntPtr(nGroups + (i * Marshal.SizeOf<IntPtr>())));
			}

			Marshal.FreeHGlobal(nTitle);
			Marshal.FreeHGlobal(nTelephones);
			Marshal.FreeHGlobal(nPresenceStatus);
			Marshal.FreeHGlobal(nPhoto);
			Marshal.FreeHGlobal(nNickname);
			Marshal.FreeHGlobal(nName);
			Marshal.FreeHGlobal(nId);
			Marshal.FreeHGlobal(nHandle);
			Marshal.FreeHGlobal(nGroups);
			Marshal.FreeHGlobal(nEmails);
			Marshal.FreeHGlobal(nDepartment);
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoContactGetdepartmentNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoContactSetdepartmentNative(IntPtr obj, IntPtr department);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoContactGetemailsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoContactSetemailsNative(IntPtr obj, IntPtr emails, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoContactGetemailsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoContactFreeemailsArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoContactGetgroupsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoContactSetgroupsNative(IntPtr obj, IntPtr groups, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoContactGetgroupsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoContactFreegroupsArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoContactGethandleNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoContactSethandleNative(IntPtr obj, IntPtr handle);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoContactGetidNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoContactSetidNative(IntPtr obj, IntPtr id);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoContactGetnameNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoContactSetnameNative(IntPtr obj, IntPtr name);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoContactGetnicknameNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoContactSetnicknameNative(IntPtr obj, IntPtr nickname);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoContactGetphotoNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoContactSetphotoNative(IntPtr obj, IntPtr photo);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern ContactPresenceState VidyoContactGetpresenceStateNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern void VidyoContactSetpresenceStateNative(IntPtr obj, ContactPresenceState presenceState);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoContactGetpresenceStatusNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoContactSetpresenceStatusNative(IntPtr obj, IntPtr presenceStatus);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern ContactSubscriptionState VidyoContactGetpublicationStateNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern void VidyoContactSetpublicationStateNative(IntPtr obj, ContactSubscriptionState publicationState);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern ContactSubscriptionState VidyoContactGetsubscriptionStateNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern void VidyoContactSetsubscriptionStateNative(IntPtr obj, ContactSubscriptionState subscriptionState);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoContactGettelephonesNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoContactSettelephonesNative(IntPtr obj, IntPtr telephones, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoContactGettelephonesArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoContactFreetelephonesArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoContactGettimestampNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoContactSettimestampNative(IntPtr obj, ulong timestamp);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoContactGettitleNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoContactSettitleNative(IntPtr obj, IntPtr title);

		public enum ContactPresenceState{
			ContactpresencestateUnavailable,
			ContactpresencestateDoNotDisturb,
			ContactpresencestateExtendedAway,
			ContactpresencestateAway,
			ContactpresencestateAvailable,
			ContactpresencestateInterestedInChat
		}
		public enum ContactSubscriptionState{
			ContactsubscriptionstateUnavailable,
			ContactsubscriptionstateNotSubscribed,
			ContactsubscriptionstatePreapproved,
			ContactsubscriptionstateAwaitingApproval,
			ContactsubscriptionstateSubscribed
		}
		public class ContactPropertyFactory
		{
#if __IOS__
			const string importLib = "__Internal";
#else
			const string importLib = "libVidyoClient";
#endif
			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			public static extern IntPtr VidyoContactPropertyConstructDefaultNative();
			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			public static extern void VidyoContactPropertyDestructNative(IntPtr obj);
			public static ContactProperty Create()
			{
				IntPtr objPtr = VidyoContactPropertyConstructDefaultNative();
				return new ContactProperty(objPtr);
			}
			public static void Destroy(ContactProperty obj)
			{
				VidyoContactPropertyDestructNative(obj.GetObjectPtr());
			}
		}
		public class ContactProperty{
#if __IOS__
			const string importLib = "__Internal";
#else
			const string importLib = "libVidyoClient";
#endif
			private IntPtr objPtr; // opaque VidyoContactProperty reference.
			public IntPtr GetObjectPtr(){
				IntPtr nTypes = Marshal.AllocHGlobal(Marshal.SizeOf<IntPtr>() * types.Count);
				int nTypesSize = 0;
				IntPtr nValue = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(value ?? string.Empty);

				foreach (String iter in types) {
					Marshal.WriteIntPtr(nTypes + (nTypesSize * Marshal.SizeOf<IntPtr>()), MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(iter ?? string.Empty));
					nTypesSize++;
				}

				VidyoContactPropertySettypesNative(objPtr, nTypes, nTypesSize);
				VidyoContactPropertySetvalueNative(objPtr, nValue);

				for (int i = 0; i < nTypesSize; i++) {
					Marshal.FreeHGlobal(Marshal.ReadIntPtr(nTypes + (i * Marshal.SizeOf<IntPtr>())));
				}

				Marshal.FreeHGlobal(nValue);
				Marshal.FreeHGlobal(nTypes);
				return objPtr;
			}
			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern IntPtr VidyoContactPropertyGettypesNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoContactPropertySettypesNative(IntPtr obj, IntPtr types, int size);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern IntPtr VidyoContactPropertyGettypesArrayNative(IntPtr obj, ref int size);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoContactPropertyFreetypesArrayNative(IntPtr obj, int size);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern IntPtr VidyoContactPropertyGetvalueNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoContactPropertySetvalueNative(IntPtr obj, IntPtr value);

			public List<String> types;
			public String value;
			public ContactProperty(IntPtr obj){
				objPtr = obj;

				List<String> csTypes = new List<String>();
				int nTypesSize = 0;
				IntPtr nTypes = VidyoContactPropertyGettypesArrayNative(VidyoContactPropertyGettypesNative(objPtr), ref nTypesSize);
				int nTypesIndex = 0;
				while (nTypesIndex < nTypesSize) {
					csTypes.Add((string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(Marshal.ReadIntPtr(nTypes + (nTypesIndex * Marshal.SizeOf(nTypes)))));
					nTypesIndex++;
				}

				types = csTypes;
				value = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoContactPropertyGetvalueNative(objPtr));
				VidyoContactPropertyFreetypesArrayNative(nTypes, nTypesSize);
			}
		};
		public String department;
		public List<ContactProperty> emails;
		public List<String> groups;
		public String handle;
		public String id;
		public String name;
		public String nickname;
		public String photo;
		public ContactPresenceState presenceState;
		public String presenceStatus;
		public ContactSubscriptionState publicationState;
		public ContactSubscriptionState subscriptionState;
		public List<ContactProperty> telephones;
		public ulong timestamp;
		public String title;
		public Contact(IntPtr obj){
			objPtr = obj;

			List<ContactProperty> csEmails = new List<ContactProperty>();
			int nEmailsSize = 0;
			IntPtr nEmails = VidyoContactGetemailsArrayNative(VidyoContactGetemailsNative(objPtr), ref nEmailsSize);
			int nEmailsIndex = 0;
			while (nEmailsIndex < nEmailsSize) {
				ContactProperty csTemails = new ContactProperty(Marshal.ReadIntPtr(nEmails + (nEmailsIndex * Marshal.SizeOf(nEmails))));
				csEmails.Add(csTemails);
				nEmailsIndex++;
			}

			List<String> csGroups = new List<String>();
			int nGroupsSize = 0;
			IntPtr nGroups = VidyoContactGetgroupsArrayNative(VidyoContactGetgroupsNative(objPtr), ref nGroupsSize);
			int nGroupsIndex = 0;
			while (nGroupsIndex < nGroupsSize) {
				csGroups.Add((string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(Marshal.ReadIntPtr(nGroups + (nGroupsIndex * Marshal.SizeOf(nGroups)))));
				nGroupsIndex++;
			}

			List<ContactProperty> csTelephones = new List<ContactProperty>();
			int nTelephonesSize = 0;
			IntPtr nTelephones = VidyoContactGettelephonesArrayNative(VidyoContactGettelephonesNative(objPtr), ref nTelephonesSize);
			int nTelephonesIndex = 0;
			while (nTelephonesIndex < nTelephonesSize) {
				ContactProperty csTtelephones = new ContactProperty(Marshal.ReadIntPtr(nTelephones + (nTelephonesIndex * Marshal.SizeOf(nTelephones))));
				csTelephones.Add(csTtelephones);
				nTelephonesIndex++;
			}

			department = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoContactGetdepartmentNative(objPtr));
			emails = csEmails;
			groups = csGroups;
			handle = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoContactGethandleNative(objPtr));
			id = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoContactGetidNative(objPtr));
			name = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoContactGetnameNative(objPtr));
			nickname = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoContactGetnicknameNative(objPtr));
			photo = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoContactGetphotoNative(objPtr));
			presenceState = VidyoContactGetpresenceStateNative(objPtr);
			presenceStatus = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoContactGetpresenceStatusNative(objPtr));
			publicationState = VidyoContactGetpublicationStateNative(objPtr);
			subscriptionState = VidyoContactGetsubscriptionStateNative(objPtr);
			telephones = csTelephones;
			timestamp = VidyoContactGettimestampNative(objPtr);
			title = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoContactGettitleNative(objPtr));
			VidyoContactFreetelephonesArrayNative(nTelephones, nTelephonesSize);
			VidyoContactFreegroupsArrayNative(nGroups, nGroupsSize);
			VidyoContactFreeemailsArrayNative(nEmails, nEmailsSize);
		}
	};
}
