// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class FormFieldOptionFactory
	{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoFormFieldOptionConstructDefaultNative();
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoFormFieldOptionDestructNative(IntPtr obj);
		public static FormFieldOption Create()
		{
			IntPtr objPtr = VidyoFormFieldOptionConstructDefaultNative();
			return new FormFieldOption(objPtr);
		}
		public static void Destroy(FormFieldOption obj)
		{
			VidyoFormFieldOptionDestructNative(obj.GetObjectPtr());
		}
	}
	public class FormFieldOption{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoFormFieldOption reference.
		public IntPtr GetObjectPtr(){
			IntPtr nValue = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(value ?? string.Empty);

			VidyoFormFieldOptionSetselectedNative(objPtr, selected);
			VidyoFormFieldOptionSetvalueNative(objPtr, nValue);

			Marshal.FreeHGlobal(nValue);
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoFormFieldOptionGetselectedNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern void VidyoFormFieldOptionSetselectedNative(IntPtr obj, Boolean selected);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoFormFieldOptionGetvalueNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoFormFieldOptionSetvalueNative(IntPtr obj, IntPtr value);

		public Boolean selected;
		public String value;
		public FormFieldOption(IntPtr obj){
			objPtr = obj;

			selected = VidyoFormFieldOptionGetselectedNative(objPtr);
			value = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoFormFieldOptionGetvalueNative(objPtr));
		}
	};
}
