// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class LocalRendererStreamStatsFactory
	{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoLocalRendererStreamStatsConstructDefaultNative();
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoLocalRendererStreamStatsDestructNative(IntPtr obj);
		public static LocalRendererStreamStats Create()
		{
			IntPtr objPtr = VidyoLocalRendererStreamStatsConstructDefaultNative();
			return new LocalRendererStreamStats(objPtr);
		}
		public static void Destroy(LocalRendererStreamStats obj)
		{
			VidyoLocalRendererStreamStatsDestructNative(obj.GetObjectPtr());
		}
	}
	public class LocalRendererStreamStats{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoLocalRendererStreamStats reference.
		public IntPtr GetObjectPtr(){
			IntPtr nId = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(id ?? string.Empty);
			IntPtr nName = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(name ?? string.Empty);

			VidyoLocalRendererStreamStatsSetbufferDroppedNative(objPtr, bufferDropped);
			VidyoLocalRendererStreamStatsSetbufferSizeNative(objPtr, bufferSize);
			VidyoLocalRendererStreamStatsSetheightNative(objPtr, height);
			VidyoLocalRendererStreamStatsSetidNative(objPtr, nId);
			VidyoLocalRendererStreamStatsSetnameNative(objPtr, nName);
			VidyoLocalRendererStreamStatsSetwidthNative(objPtr, width);

			Marshal.FreeHGlobal(nName);
			Marshal.FreeHGlobal(nId);
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoLocalRendererStreamStatsGetbufferDroppedNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoLocalRendererStreamStatsSetbufferDroppedNative(IntPtr obj, uint bufferDropped);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoLocalRendererStreamStatsGetbufferSizeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoLocalRendererStreamStatsSetbufferSizeNative(IntPtr obj, uint bufferSize);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoLocalRendererStreamStatsGetheightNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoLocalRendererStreamStatsSetheightNative(IntPtr obj, ulong height);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLocalRendererStreamStatsGetidNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoLocalRendererStreamStatsSetidNative(IntPtr obj, IntPtr id);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLocalRendererStreamStatsGetnameNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoLocalRendererStreamStatsSetnameNative(IntPtr obj, IntPtr name);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoLocalRendererStreamStatsGetwidthNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoLocalRendererStreamStatsSetwidthNative(IntPtr obj, ulong width);

		public uint bufferDropped;
		public uint bufferSize;
		public ulong height;
		public String id;
		public String name;
		public ulong width;
		public LocalRendererStreamStats(IntPtr obj){
			objPtr = obj;

			bufferDropped = VidyoLocalRendererStreamStatsGetbufferDroppedNative(objPtr);
			bufferSize = VidyoLocalRendererStreamStatsGetbufferSizeNative(objPtr);
			height = VidyoLocalRendererStreamStatsGetheightNative(objPtr);
			id = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoLocalRendererStreamStatsGetidNative(objPtr));
			name = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoLocalRendererStreamStatsGetnameNative(objPtr));
			width = VidyoLocalRendererStreamStatsGetwidthNative(objPtr);
		}
	};
}
