// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class LogStatsFactory
	{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoLogStatsConstructDefaultNative();
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoLogStatsDestructNative(IntPtr obj);
		public static LogStats Create()
		{
			IntPtr objPtr = VidyoLogStatsConstructDefaultNative();
			return new LogStats(objPtr);
		}
		public static void Destroy(LogStats obj)
		{
			VidyoLogStatsDestructNative(obj.GetObjectPtr());
		}
	}
	public class LogStats{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoLogStats reference.
		public IntPtr GetObjectPtr(){
			IntPtr nLogErrorDataStats = Marshal.AllocHGlobal(Marshal.SizeOf<IntPtr>() * logErrorDataStats.Count);
			int nLogErrorDataStatsSize = 0;
			IntPtr nLogWarningDataStats = Marshal.AllocHGlobal(Marshal.SizeOf<IntPtr>() * logWarningDataStats.Count);
			int nLogWarningDataStatsSize = 0;

			foreach (LogDataStats iter in logErrorDataStats) {
				Marshal.WriteIntPtr(nLogErrorDataStats + (nLogErrorDataStatsSize * Marshal.SizeOf<IntPtr>()), iter.GetObjectPtr());
				nLogErrorDataStatsSize++;
			}
			foreach (LogDataStats iter in logWarningDataStats) {
				Marshal.WriteIntPtr(nLogWarningDataStats + (nLogWarningDataStatsSize * Marshal.SizeOf<IntPtr>()), iter.GetObjectPtr());
				nLogWarningDataStatsSize++;
			}

			VidyoLogStatsSetlogErrorDataStatsNative(objPtr, nLogErrorDataStats, nLogErrorDataStatsSize);
			VidyoLogStatsSetlogWarningDataStatsNative(objPtr, nLogWarningDataStats, nLogWarningDataStatsSize);

			Marshal.FreeHGlobal(nLogWarningDataStats);
			Marshal.FreeHGlobal(nLogErrorDataStats);
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLogStatsGetlogErrorDataStatsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoLogStatsSetlogErrorDataStatsNative(IntPtr obj, IntPtr logErrorDataStats, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLogStatsGetlogErrorDataStatsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoLogStatsFreelogErrorDataStatsArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLogStatsGetlogWarningDataStatsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoLogStatsSetlogWarningDataStatsNative(IntPtr obj, IntPtr logWarningDataStats, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoLogStatsGetlogWarningDataStatsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoLogStatsFreelogWarningDataStatsArrayNative(IntPtr obj, int size);

		public List<LogDataStats> logErrorDataStats;
		public List<LogDataStats> logWarningDataStats;
		public LogStats(IntPtr obj){
			objPtr = obj;

			List<LogDataStats> csLogErrorDataStats = new List<LogDataStats>();
			int nLogErrorDataStatsSize = 0;
			IntPtr nLogErrorDataStats = VidyoLogStatsGetlogErrorDataStatsArrayNative(VidyoLogStatsGetlogErrorDataStatsNative(objPtr), ref nLogErrorDataStatsSize);
			int nLogErrorDataStatsIndex = 0;
			while (nLogErrorDataStatsIndex < nLogErrorDataStatsSize) {
				LogDataStats csTlogErrorDataStats = new LogDataStats(Marshal.ReadIntPtr(nLogErrorDataStats + (nLogErrorDataStatsIndex * Marshal.SizeOf(nLogErrorDataStats))));
				csLogErrorDataStats.Add(csTlogErrorDataStats);
				nLogErrorDataStatsIndex++;
			}

			List<LogDataStats> csLogWarningDataStats = new List<LogDataStats>();
			int nLogWarningDataStatsSize = 0;
			IntPtr nLogWarningDataStats = VidyoLogStatsGetlogWarningDataStatsArrayNative(VidyoLogStatsGetlogWarningDataStatsNative(objPtr), ref nLogWarningDataStatsSize);
			int nLogWarningDataStatsIndex = 0;
			while (nLogWarningDataStatsIndex < nLogWarningDataStatsSize) {
				LogDataStats csTlogWarningDataStats = new LogDataStats(Marshal.ReadIntPtr(nLogWarningDataStats + (nLogWarningDataStatsIndex * Marshal.SizeOf(nLogWarningDataStats))));
				csLogWarningDataStats.Add(csTlogWarningDataStats);
				nLogWarningDataStatsIndex++;
			}

			logErrorDataStats = csLogErrorDataStats;
			logWarningDataStats = csLogWarningDataStats;
			VidyoLogStatsFreelogWarningDataStatsArrayNative(nLogWarningDataStats, nLogWarningDataStatsSize);
			VidyoLogStatsFreelogErrorDataStatsArrayNative(nLogErrorDataStats, nLogErrorDataStatsSize);
		}
	};
}
