// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class MeetingAttendeeFactory
	{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoMeetingAttendeeConstructDefaultNative();
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoMeetingAttendeeDestructNative(IntPtr obj);
		public static MeetingAttendee Create()
		{
			IntPtr objPtr = VidyoMeetingAttendeeConstructDefaultNative();
			return new MeetingAttendee(objPtr);
		}
		public static void Destroy(MeetingAttendee obj)
		{
			VidyoMeetingAttendeeDestructNative(obj.GetObjectPtr());
		}
	}
	public class MeetingAttendee{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoMeetingAttendee reference.
		public IntPtr GetObjectPtr(){
			IntPtr nEmail = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(email ?? string.Empty);
			IntPtr nName = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(name ?? string.Empty);

			VidyoMeetingAttendeeSetemailNative(objPtr, nEmail);
			VidyoMeetingAttendeeSetnameNative(objPtr, nName);
			VidyoMeetingAttendeeSetroleNative(objPtr, role);
			VidyoMeetingAttendeeSetstatusNative(objPtr, status);

			Marshal.FreeHGlobal(nName);
			Marshal.FreeHGlobal(nEmail);
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoMeetingAttendeeGetemailNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoMeetingAttendeeSetemailNative(IntPtr obj, IntPtr email);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoMeetingAttendeeGetnameNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoMeetingAttendeeSetnameNative(IntPtr obj, IntPtr name);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern AttendeeParticipationRole VidyoMeetingAttendeeGetroleNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern void VidyoMeetingAttendeeSetroleNative(IntPtr obj, AttendeeParticipationRole role);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern AttendeeParticipationStatus VidyoMeetingAttendeeGetstatusNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern void VidyoMeetingAttendeeSetstatusNative(IntPtr obj, AttendeeParticipationStatus status);

		public enum AttendeeParticipationRole{
			AttendeeparticipationroleChair,
			AttendeeparticipationroleRequired,
			AttendeeparticipationroleOptional,
			AttendeeparticipationroleInformational
		}
		public enum AttendeeParticipationStatus{
			AttendeeparticipationstatusNeedsAction,
			AttendeeparticipationstatusOrganized,
			AttendeeparticipationstatusAccepted,
			AttendeeparticipationstatusDeclined,
			AttendeeparticipationstatusTentative,
			AttendeeparticipationstatusDelegated,
			AttendeeparticipationstatusNone,
			AttendeeparticipationstatusCompleted,
			AttendeeparticipationstatusInProcess
		}
		public String email;
		public String name;
		public AttendeeParticipationRole role;
		public AttendeeParticipationStatus status;
		public MeetingAttendee(IntPtr obj){
			objPtr = obj;

			email = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoMeetingAttendeeGetemailNative(objPtr));
			name = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoMeetingAttendeeGetnameNative(objPtr));
			role = VidyoMeetingAttendeeGetroleNative(objPtr);
			status = VidyoMeetingAttendeeGetstatusNative(objPtr);
		}
	};
}
