// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class MeetingInfoFactory
	{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoMeetingInfoConstructDefaultNative();
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoMeetingInfoDestructNative(IntPtr obj);
		public static MeetingInfo Create()
		{
			IntPtr objPtr = VidyoMeetingInfoConstructDefaultNative();
			return new MeetingInfo(objPtr);
		}
		public static void Destroy(MeetingInfo obj)
		{
			VidyoMeetingInfoDestructNative(obj.GetObjectPtr());
		}
	}
	public class MeetingInfo{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoMeetingInfo reference.
		public IntPtr GetObjectPtr(){
			IntPtr nAttendees = Marshal.AllocHGlobal(Marshal.SizeOf<IntPtr>() * attendees.Count);
			int nAttendeesSize = 0;
			IntPtr nBody = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(body ?? string.Empty);
			IntPtr nEndDateTime = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(endDateTime ?? string.Empty);
			IntPtr nId = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(id ?? string.Empty);
			IntPtr nLocation = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(location ?? string.Empty);
			IntPtr nOwnerEmail = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(ownerEmail ?? string.Empty);
			IntPtr nOwnerName = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(ownerName ?? string.Empty);
			IntPtr nStartDateTime = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(startDateTime ?? string.Empty);
			IntPtr nSubject = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(subject ?? string.Empty);
			IntPtr nVidyoMeetingRoomLink = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(vidyoMeetingRoomLink ?? string.Empty);

			foreach (MeetingAttendee iter in attendees) {
				Marshal.WriteIntPtr(nAttendees + (nAttendeesSize * Marshal.SizeOf<IntPtr>()), iter.GetObjectPtr());
				nAttendeesSize++;
			}

			VidyoMeetingInfoSetattendeesNative(objPtr, nAttendees, nAttendeesSize);
			VidyoMeetingInfoSetbodyNative(objPtr, nBody);
			VidyoMeetingInfoSetendDateTimeNative(objPtr, nEndDateTime);
			VidyoMeetingInfoSetidNative(objPtr, nId);
			VidyoMeetingInfoSetisVidyoMeetingNative(objPtr, isVidyoMeeting);
			VidyoMeetingInfoSetlocationNative(objPtr, nLocation);
			VidyoMeetingInfoSetnumOfAttendeesNative(objPtr, numOfAttendees);
			VidyoMeetingInfoSetownerEmailNative(objPtr, nOwnerEmail);
			VidyoMeetingInfoSetownerNameNative(objPtr, nOwnerName);
			VidyoMeetingInfoSetstartDateTimeNative(objPtr, nStartDateTime);
			VidyoMeetingInfoSetsubjectNative(objPtr, nSubject);
			VidyoMeetingInfoSettotalBodyLengthNative(objPtr, totalBodyLength);
			VidyoMeetingInfoSetvidyoMeetingRoomLinkNative(objPtr, nVidyoMeetingRoomLink);

			Marshal.FreeHGlobal(nVidyoMeetingRoomLink);
			Marshal.FreeHGlobal(nSubject);
			Marshal.FreeHGlobal(nStartDateTime);
			Marshal.FreeHGlobal(nOwnerName);
			Marshal.FreeHGlobal(nOwnerEmail);
			Marshal.FreeHGlobal(nLocation);
			Marshal.FreeHGlobal(nId);
			Marshal.FreeHGlobal(nEndDateTime);
			Marshal.FreeHGlobal(nBody);
			Marshal.FreeHGlobal(nAttendees);
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoMeetingInfoGetattendeesNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoMeetingInfoSetattendeesNative(IntPtr obj, IntPtr attendees, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoMeetingInfoGetattendeesArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoMeetingInfoFreeattendeesArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoMeetingInfoGetbodyNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoMeetingInfoSetbodyNative(IntPtr obj, IntPtr body);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoMeetingInfoGetendDateTimeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoMeetingInfoSetendDateTimeNative(IntPtr obj, IntPtr endDateTime);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoMeetingInfoGetidNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoMeetingInfoSetidNative(IntPtr obj, IntPtr id);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoMeetingInfoGetisVidyoMeetingNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern void VidyoMeetingInfoSetisVidyoMeetingNative(IntPtr obj, Boolean isVidyoMeeting);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoMeetingInfoGetlocationNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoMeetingInfoSetlocationNative(IntPtr obj, IntPtr location);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoMeetingInfoGetnumOfAttendeesNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoMeetingInfoSetnumOfAttendeesNative(IntPtr obj, uint numOfAttendees);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoMeetingInfoGetownerEmailNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoMeetingInfoSetownerEmailNative(IntPtr obj, IntPtr ownerEmail);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoMeetingInfoGetownerNameNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoMeetingInfoSetownerNameNative(IntPtr obj, IntPtr ownerName);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoMeetingInfoGetstartDateTimeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoMeetingInfoSetstartDateTimeNative(IntPtr obj, IntPtr startDateTime);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoMeetingInfoGetsubjectNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoMeetingInfoSetsubjectNative(IntPtr obj, IntPtr subject);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoMeetingInfoGettotalBodyLengthNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoMeetingInfoSettotalBodyLengthNative(IntPtr obj, ulong totalBodyLength);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoMeetingInfoGetvidyoMeetingRoomLinkNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoMeetingInfoSetvidyoMeetingRoomLinkNative(IntPtr obj, IntPtr vidyoMeetingRoomLink);

		public List<MeetingAttendee> attendees;
		public String body;
		public String endDateTime;
		public String id;
		public Boolean isVidyoMeeting;
		public String location;
		public uint numOfAttendees;
		public String ownerEmail;
		public String ownerName;
		public String startDateTime;
		public String subject;
		public ulong totalBodyLength;
		public String vidyoMeetingRoomLink;
		public MeetingInfo(IntPtr obj){
			objPtr = obj;

			List<MeetingAttendee> csAttendees = new List<MeetingAttendee>();
			int nAttendeesSize = 0;
			IntPtr nAttendees = VidyoMeetingInfoGetattendeesArrayNative(VidyoMeetingInfoGetattendeesNative(objPtr), ref nAttendeesSize);
			int nAttendeesIndex = 0;
			while (nAttendeesIndex < nAttendeesSize) {
				MeetingAttendee csTattendees = new MeetingAttendee(Marshal.ReadIntPtr(nAttendees + (nAttendeesIndex * Marshal.SizeOf(nAttendees))));
				csAttendees.Add(csTattendees);
				nAttendeesIndex++;
			}

			attendees = csAttendees;
			body = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoMeetingInfoGetbodyNative(objPtr));
			endDateTime = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoMeetingInfoGetendDateTimeNative(objPtr));
			id = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoMeetingInfoGetidNative(objPtr));
			isVidyoMeeting = VidyoMeetingInfoGetisVidyoMeetingNative(objPtr);
			location = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoMeetingInfoGetlocationNative(objPtr));
			numOfAttendees = VidyoMeetingInfoGetnumOfAttendeesNative(objPtr);
			ownerEmail = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoMeetingInfoGetownerEmailNative(objPtr));
			ownerName = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoMeetingInfoGetownerNameNative(objPtr));
			startDateTime = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoMeetingInfoGetstartDateTimeNative(objPtr));
			subject = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoMeetingInfoGetsubjectNative(objPtr));
			totalBodyLength = VidyoMeetingInfoGettotalBodyLengthNative(objPtr);
			vidyoMeetingRoomLink = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoMeetingInfoGetvidyoMeetingRoomLinkNative(objPtr));
			VidyoMeetingInfoFreeattendeesArrayNative(nAttendees, nAttendeesSize);
		}
	};
}
