// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class PropertyFactory
	{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoPropertyConstructDefaultNative();
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoPropertyDestructNative(IntPtr obj);
		public static Property Create()
		{
			IntPtr objPtr = VidyoPropertyConstructDefaultNative();
			return new Property(objPtr);
		}
		public static void Destroy(Property obj)
		{
			VidyoPropertyDestructNative(obj.GetObjectPtr());
		}
	}
	public class Property{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoProperty reference.
		public IntPtr GetObjectPtr(){
			IntPtr nName = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(name ?? string.Empty);
			IntPtr nValue = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(value ?? string.Empty);

			VidyoPropertySetnameNative(objPtr, nName);
			VidyoPropertySetvalueNative(objPtr, nValue);

			Marshal.FreeHGlobal(nValue);
			Marshal.FreeHGlobal(nName);
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoPropertyGetnameNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoPropertySetnameNative(IntPtr obj, IntPtr name);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoPropertyGetvalueNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoPropertySetvalueNative(IntPtr obj, IntPtr value);

		public String name;
		public String value;
		public Property(IntPtr obj){
			objPtr = obj;

			name = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoPropertyGetnameNative(objPtr));
			value = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoPropertyGetvalueNative(objPtr));
		}
	};
}
