// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class RateShaperStatsFactory
	{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoRateShaperStatsConstructDefaultNative();
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoRateShaperStatsDestructNative(IntPtr obj);
		public static RateShaperStats Create()
		{
			IntPtr objPtr = VidyoRateShaperStatsConstructDefaultNative();
			return new RateShaperStats(objPtr);
		}
		public static void Destroy(RateShaperStats obj)
		{
			VidyoRateShaperStatsDestructNative(obj.GetObjectPtr());
		}
	}
	public class RateShaperStats{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoRateShaperStats reference.
		public IntPtr GetObjectPtr(){

			VidyoRateShaperStatsSetdelayNormalNative(objPtr, delayNormal);
			VidyoRateShaperStatsSetdelayRetransmitNative(objPtr, delayRetransmit);
			VidyoRateShaperStatsSetdropNormalNative(objPtr, dropNormal);
			VidyoRateShaperStatsSetpacketsNormalNative(objPtr, packetsNormal);
			VidyoRateShaperStatsSetpacketsRetransmitNative(objPtr, packetsRetransmit);

			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoRateShaperStatsGetdelayNormalNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRateShaperStatsSetdelayNormalNative(IntPtr obj, uint delayNormal);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoRateShaperStatsGetdelayRetransmitNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRateShaperStatsSetdelayRetransmitNative(IntPtr obj, uint delayRetransmit);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoRateShaperStatsGetdropNormalNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRateShaperStatsSetdropNormalNative(IntPtr obj, uint dropNormal);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoRateShaperStatsGetpacketsNormalNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRateShaperStatsSetpacketsNormalNative(IntPtr obj, uint packetsNormal);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoRateShaperStatsGetpacketsRetransmitNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRateShaperStatsSetpacketsRetransmitNative(IntPtr obj, uint packetsRetransmit);

		public uint delayNormal;
		public uint delayRetransmit;
		public uint dropNormal;
		public uint packetsNormal;
		public uint packetsRetransmit;
		public RateShaperStats(IntPtr obj){
			objPtr = obj;

			delayNormal = VidyoRateShaperStatsGetdelayNormalNative(objPtr);
			delayRetransmit = VidyoRateShaperStatsGetdelayRetransmitNative(objPtr);
			dropNormal = VidyoRateShaperStatsGetdropNormalNative(objPtr);
			packetsNormal = VidyoRateShaperStatsGetpacketsNormalNative(objPtr);
			packetsRetransmit = VidyoRateShaperStatsGetpacketsRetransmitNative(objPtr);
		}
	};
}
