// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class RemoteVideoSourceStatsFactory
	{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoRemoteVideoSourceStatsConstructDefaultNative();
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoRemoteVideoSourceStatsDestructNative(IntPtr obj);
		public static RemoteVideoSourceStats Create()
		{
			IntPtr objPtr = VidyoRemoteVideoSourceStatsConstructDefaultNative();
			return new RemoteVideoSourceStats(objPtr);
		}
		public static void Destroy(RemoteVideoSourceStats obj)
		{
			VidyoRemoteVideoSourceStatsDestructNative(obj.GetObjectPtr());
		}
	}
	public class RemoteVideoSourceStats{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoRemoteVideoSourceStats reference.
		public IntPtr GetObjectPtr(){
			IntPtr nCodecName = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(codecName ?? string.Empty);
			IntPtr nId = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(id ?? string.Empty);
			IntPtr nLocalRendererStreams = Marshal.AllocHGlobal(Marshal.SizeOf<IntPtr>() * localRendererStreams.Count);
			int nLocalRendererStreamsSize = 0;
			IntPtr nName = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(name ?? string.Empty);
			IntPtr nShowState = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(showState ?? string.Empty);

			foreach (LocalRendererStreamStats iter in localRendererStreams) {
				Marshal.WriteIntPtr(nLocalRendererStreams + (nLocalRendererStreamsSize * Marshal.SizeOf<IntPtr>()), iter.GetObjectPtr());
				nLocalRendererStreamsSize++;
			}

			VidyoRemoteVideoSourceStatsSetcodecFirNative(objPtr, codecFir);
			VidyoRemoteVideoSourceStatsSetcodecIFramesNative(objPtr, codecIFrames);
			VidyoRemoteVideoSourceStatsSetcodecLayersNative(objPtr, codecLayers);
			VidyoRemoteVideoSourceStatsSetcodecNacksNative(objPtr, codecNacks);
			VidyoRemoteVideoSourceStatsSetcodecNameNative(objPtr, nCodecName);
			VidyoRemoteVideoSourceStatsSetfpsDecodedNative(objPtr, fpsDecoded);
			VidyoRemoteVideoSourceStatsSetfpsDecoderInputNative(objPtr, fpsDecoderInput);
			VidyoRemoteVideoSourceStatsSetfpsRenderedNative(objPtr, fpsRendered);
			VidyoRemoteVideoSourceStatsSetheightNative(objPtr, height);
			VidyoRemoteVideoSourceStatsSetidNative(objPtr, nId);
			VidyoRemoteVideoSourceStatsSetlastFrameMsNative(objPtr, lastFrameMs);
			VidyoRemoteVideoSourceStatsSetlocalRendererStreamsNative(objPtr, nLocalRendererStreams, nLocalRendererStreamsSize);
			VidyoRemoteVideoSourceStatsSetmaxStreamFrameRateNative(objPtr, maxStreamFrameRate);
			VidyoRemoteVideoSourceStatsSetmaxStreamHeightNative(objPtr, maxStreamHeight);
			VidyoRemoteVideoSourceStatsSetmaxStreamWidthNative(objPtr, maxStreamWidth);
			VidyoRemoteVideoSourceStatsSetnameNative(objPtr, nName);
			VidyoRemoteVideoSourceStatsSetreceiveNetworkBitRateNative(objPtr, receiveNetworkBitRate);
			VidyoRemoteVideoSourceStatsSetreceiveNetworkPacketsConcealedNative(objPtr, receiveNetworkPacketsConcealed);
			VidyoRemoteVideoSourceStatsSetreceiveNetworkPacketsLostNative(objPtr, receiveNetworkPacketsLost);
			VidyoRemoteVideoSourceStatsSetreceiveNetworkPacketsReorderedNative(objPtr, receiveNetworkPacketsReordered);
			VidyoRemoteVideoSourceStatsSetreceiveNetworkRecoveredWithFecNative(objPtr, receiveNetworkRecoveredWithFec);
			VidyoRemoteVideoSourceStatsSetshowFrameRateNative(objPtr, showFrameRate);
			VidyoRemoteVideoSourceStatsSetshowHeightNative(objPtr, showHeight);
			VidyoRemoteVideoSourceStatsSetshowPixelRateNative(objPtr, showPixelRate);
			VidyoRemoteVideoSourceStatsSetshowStateNative(objPtr, nShowState);
			VidyoRemoteVideoSourceStatsSetshowWidthNative(objPtr, showWidth);
			VidyoRemoteVideoSourceStatsSetvideoDeltaFromAudioMsNative(objPtr, videoDeltaFromAudioMs);
			VidyoRemoteVideoSourceStatsSetwidthNative(objPtr, width);

			Marshal.FreeHGlobal(nShowState);
			Marshal.FreeHGlobal(nName);
			Marshal.FreeHGlobal(nLocalRendererStreams);
			Marshal.FreeHGlobal(nId);
			Marshal.FreeHGlobal(nCodecName);
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetcodecFirNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetcodecFirNative(IntPtr obj, ulong codecFir);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetcodecIFramesNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetcodecIFramesNative(IntPtr obj, ulong codecIFrames);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetcodecLayersNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetcodecLayersNative(IntPtr obj, ulong codecLayers);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetcodecNacksNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetcodecNacksNative(IntPtr obj, ulong codecNacks);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRemoteVideoSourceStatsGetcodecNameNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetcodecNameNative(IntPtr obj, IntPtr codecName);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetfpsDecodedNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetfpsDecodedNative(IntPtr obj, ulong fpsDecoded);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetfpsDecoderInputNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetfpsDecoderInputNative(IntPtr obj, ulong fpsDecoderInput);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetfpsRenderedNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetfpsRenderedNative(IntPtr obj, ulong fpsRendered);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetheightNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetheightNative(IntPtr obj, ulong height);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRemoteVideoSourceStatsGetidNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetidNative(IntPtr obj, IntPtr id);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern int VidyoRemoteVideoSourceStatsGetlastFrameMsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetlastFrameMsNative(IntPtr obj, int lastFrameMs);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRemoteVideoSourceStatsGetlocalRendererStreamsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetlocalRendererStreamsNative(IntPtr obj, IntPtr localRendererStreams, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRemoteVideoSourceStatsGetlocalRendererStreamsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsFreelocalRendererStreamsArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoRemoteVideoSourceStatsGetmaxStreamFrameRateNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetmaxStreamFrameRateNative(IntPtr obj, uint maxStreamFrameRate);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetmaxStreamHeightNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetmaxStreamHeightNative(IntPtr obj, ulong maxStreamHeight);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetmaxStreamWidthNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetmaxStreamWidthNative(IntPtr obj, ulong maxStreamWidth);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRemoteVideoSourceStatsGetnameNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetnameNative(IntPtr obj, IntPtr name);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetreceiveNetworkBitRateNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetreceiveNetworkBitRateNative(IntPtr obj, ulong receiveNetworkBitRate);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetreceiveNetworkPacketsConcealedNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetreceiveNetworkPacketsConcealedNative(IntPtr obj, ulong receiveNetworkPacketsConcealed);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetreceiveNetworkPacketsLostNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetreceiveNetworkPacketsLostNative(IntPtr obj, ulong receiveNetworkPacketsLost);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetreceiveNetworkPacketsReorderedNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetreceiveNetworkPacketsReorderedNative(IntPtr obj, ulong receiveNetworkPacketsReordered);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetreceiveNetworkRecoveredWithFecNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetreceiveNetworkRecoveredWithFecNative(IntPtr obj, ulong receiveNetworkRecoveredWithFec);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoRemoteVideoSourceStatsGetshowFrameRateNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetshowFrameRateNative(IntPtr obj, uint showFrameRate);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetshowHeightNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetshowHeightNative(IntPtr obj, ulong showHeight);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetshowPixelRateNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetshowPixelRateNative(IntPtr obj, ulong showPixelRate);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRemoteVideoSourceStatsGetshowStateNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetshowStateNative(IntPtr obj, IntPtr showState);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetshowWidthNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetshowWidthNative(IntPtr obj, ulong showWidth);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern int VidyoRemoteVideoSourceStatsGetvideoDeltaFromAudioMsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetvideoDeltaFromAudioMsNative(IntPtr obj, int videoDeltaFromAudioMs);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteVideoSourceStatsGetwidthNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteVideoSourceStatsSetwidthNative(IntPtr obj, ulong width);

		public ulong codecFir;
		public ulong codecIFrames;
		public ulong codecLayers;
		public ulong codecNacks;
		public String codecName;
		public ulong fpsDecoded;
		public ulong fpsDecoderInput;
		public ulong fpsRendered;
		public ulong height;
		public String id;
		public int lastFrameMs;
		public List<LocalRendererStreamStats> localRendererStreams;
		public uint maxStreamFrameRate;
		public ulong maxStreamHeight;
		public ulong maxStreamWidth;
		public String name;
		public ulong receiveNetworkBitRate;
		public ulong receiveNetworkPacketsConcealed;
		public ulong receiveNetworkPacketsLost;
		public ulong receiveNetworkPacketsReordered;
		public ulong receiveNetworkRecoveredWithFec;
		public uint showFrameRate;
		public ulong showHeight;
		public ulong showPixelRate;
		public String showState;
		public ulong showWidth;
		public int videoDeltaFromAudioMs;
		public ulong width;
		public RemoteVideoSourceStats(IntPtr obj){
			objPtr = obj;

			List<LocalRendererStreamStats> csLocalRendererStreams = new List<LocalRendererStreamStats>();
			int nLocalRendererStreamsSize = 0;
			IntPtr nLocalRendererStreams = VidyoRemoteVideoSourceStatsGetlocalRendererStreamsArrayNative(VidyoRemoteVideoSourceStatsGetlocalRendererStreamsNative(objPtr), ref nLocalRendererStreamsSize);
			int nLocalRendererStreamsIndex = 0;
			while (nLocalRendererStreamsIndex < nLocalRendererStreamsSize) {
				LocalRendererStreamStats csTlocalRendererStreams = new LocalRendererStreamStats(Marshal.ReadIntPtr(nLocalRendererStreams + (nLocalRendererStreamsIndex * Marshal.SizeOf(nLocalRendererStreams))));
				csLocalRendererStreams.Add(csTlocalRendererStreams);
				nLocalRendererStreamsIndex++;
			}

			codecFir = VidyoRemoteVideoSourceStatsGetcodecFirNative(objPtr);
			codecIFrames = VidyoRemoteVideoSourceStatsGetcodecIFramesNative(objPtr);
			codecLayers = VidyoRemoteVideoSourceStatsGetcodecLayersNative(objPtr);
			codecNacks = VidyoRemoteVideoSourceStatsGetcodecNacksNative(objPtr);
			codecName = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoRemoteVideoSourceStatsGetcodecNameNative(objPtr));
			fpsDecoded = VidyoRemoteVideoSourceStatsGetfpsDecodedNative(objPtr);
			fpsDecoderInput = VidyoRemoteVideoSourceStatsGetfpsDecoderInputNative(objPtr);
			fpsRendered = VidyoRemoteVideoSourceStatsGetfpsRenderedNative(objPtr);
			height = VidyoRemoteVideoSourceStatsGetheightNative(objPtr);
			id = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoRemoteVideoSourceStatsGetidNative(objPtr));
			lastFrameMs = VidyoRemoteVideoSourceStatsGetlastFrameMsNative(objPtr);
			localRendererStreams = csLocalRendererStreams;
			maxStreamFrameRate = VidyoRemoteVideoSourceStatsGetmaxStreamFrameRateNative(objPtr);
			maxStreamHeight = VidyoRemoteVideoSourceStatsGetmaxStreamHeightNative(objPtr);
			maxStreamWidth = VidyoRemoteVideoSourceStatsGetmaxStreamWidthNative(objPtr);
			name = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoRemoteVideoSourceStatsGetnameNative(objPtr));
			receiveNetworkBitRate = VidyoRemoteVideoSourceStatsGetreceiveNetworkBitRateNative(objPtr);
			receiveNetworkPacketsConcealed = VidyoRemoteVideoSourceStatsGetreceiveNetworkPacketsConcealedNative(objPtr);
			receiveNetworkPacketsLost = VidyoRemoteVideoSourceStatsGetreceiveNetworkPacketsLostNative(objPtr);
			receiveNetworkPacketsReordered = VidyoRemoteVideoSourceStatsGetreceiveNetworkPacketsReorderedNative(objPtr);
			receiveNetworkRecoveredWithFec = VidyoRemoteVideoSourceStatsGetreceiveNetworkRecoveredWithFecNative(objPtr);
			showFrameRate = VidyoRemoteVideoSourceStatsGetshowFrameRateNative(objPtr);
			showHeight = VidyoRemoteVideoSourceStatsGetshowHeightNative(objPtr);
			showPixelRate = VidyoRemoteVideoSourceStatsGetshowPixelRateNative(objPtr);
			showState = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoRemoteVideoSourceStatsGetshowStateNative(objPtr));
			showWidth = VidyoRemoteVideoSourceStatsGetshowWidthNative(objPtr);
			videoDeltaFromAudioMs = VidyoRemoteVideoSourceStatsGetvideoDeltaFromAudioMsNative(objPtr);
			width = VidyoRemoteVideoSourceStatsGetwidthNative(objPtr);
			VidyoRemoteVideoSourceStatsFreelocalRendererStreamsArrayNative(nLocalRendererStreams, nLocalRendererStreamsSize);
		}
	};
}
