// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class RoomInfoFactory
	{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoRoomInfoConstructDefaultNative();
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoRoomInfoDestructNative(IntPtr obj);
		public static RoomInfo Create()
		{
			IntPtr objPtr = VidyoRoomInfoConstructDefaultNative();
			return new RoomInfo(objPtr);
		}
		public static void Destroy(RoomInfo obj)
		{
			VidyoRoomInfoDestructNative(obj.GetObjectPtr());
		}
	}
	public class RoomInfo{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoRoomInfo reference.
		public IntPtr GetObjectPtr(){
			IntPtr nDescription = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(description ?? string.Empty);
			IntPtr nExtension = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(extension ?? string.Empty);
			IntPtr nId = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(id ?? string.Empty);
			IntPtr nLanguage = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(language ?? string.Empty);
			IntPtr nMessageList = Marshal.AllocHGlobal(Marshal.SizeOf<IntPtr>() * messageList.Count);
			int nMessageListSize = 0;
			IntPtr nName = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(name ?? string.Empty);
			IntPtr nOwnerList = Marshal.AllocHGlobal(Marshal.SizeOf<IntPtr>() * ownerList.Count);
			int nOwnerListSize = 0;
			IntPtr nUserList = Marshal.AllocHGlobal(Marshal.SizeOf<IntPtr>() * userList.Count);
			int nUserListSize = 0;

			foreach (ChatMessage iter in messageList) {
				Marshal.WriteIntPtr(nMessageList + (nMessageListSize * Marshal.SizeOf<IntPtr>()), iter.GetObjectPtr());
				nMessageListSize++;
			}
			foreach (String iter in ownerList) {
				Marshal.WriteIntPtr(nOwnerList + (nOwnerListSize * Marshal.SizeOf<IntPtr>()), MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(iter ?? string.Empty));
				nOwnerListSize++;
			}
			foreach (String iter in userList) {
				Marshal.WriteIntPtr(nUserList + (nUserListSize * Marshal.SizeOf<IntPtr>()), MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(iter ?? string.Empty));
				nUserListSize++;
			}

			VidyoRoomInfoSetcreationTimeNative(objPtr, creationTime);
			VidyoRoomInfoSetdescriptionNative(objPtr, nDescription);
			VidyoRoomInfoSetextensionNative(objPtr, nExtension);
			VidyoRoomInfoSetidNative(objPtr, nId);
			VidyoRoomInfoSetisFavoriteNative(objPtr, isFavorite);
			VidyoRoomInfoSetisMembersOnlyNative(objPtr, isMembersOnly);
			VidyoRoomInfoSetisPasswordProtectedNative(objPtr, isPasswordProtected);
			VidyoRoomInfoSetisPublicNative(objPtr, isPublic);
			VidyoRoomInfoSetisRoleChangeAllowedNative(objPtr, isRoleChangeAllowed);
			VidyoRoomInfoSetlanguageNative(objPtr, nLanguage);
			VidyoRoomInfoSetmaxParticipantsNative(objPtr, maxParticipants);
			VidyoRoomInfoSetmessageListNative(objPtr, nMessageList, nMessageListSize);
			VidyoRoomInfoSetnameNative(objPtr, nName);
			VidyoRoomInfoSetnumUsersNative(objPtr, numUsers);
			VidyoRoomInfoSetownerListNative(objPtr, nOwnerList, nOwnerListSize);
			VidyoRoomInfoSettypeNative(objPtr, type);
			VidyoRoomInfoSetuserListNative(objPtr, nUserList, nUserListSize);

			for (int i = 0; i < nOwnerListSize; i++) {
				Marshal.FreeHGlobal(Marshal.ReadIntPtr(nOwnerList + (i * Marshal.SizeOf<IntPtr>())));
			}
			for (int i = 0; i < nUserListSize; i++) {
				Marshal.FreeHGlobal(Marshal.ReadIntPtr(nUserList + (i * Marshal.SizeOf<IntPtr>())));
			}

			Marshal.FreeHGlobal(nUserList);
			Marshal.FreeHGlobal(nOwnerList);
			Marshal.FreeHGlobal(nName);
			Marshal.FreeHGlobal(nMessageList);
			Marshal.FreeHGlobal(nLanguage);
			Marshal.FreeHGlobal(nId);
			Marshal.FreeHGlobal(nExtension);
			Marshal.FreeHGlobal(nDescription);
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRoomInfoGetcreationTimeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRoomInfoSetcreationTimeNative(IntPtr obj, ulong creationTime);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetdescriptionNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRoomInfoSetdescriptionNative(IntPtr obj, IntPtr description);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetextensionNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRoomInfoSetextensionNative(IntPtr obj, IntPtr extension);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetidNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRoomInfoSetidNative(IntPtr obj, IntPtr id);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRoomInfoGetisFavoriteNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern void VidyoRoomInfoSetisFavoriteNative(IntPtr obj, Boolean isFavorite);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRoomInfoGetisMembersOnlyNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern void VidyoRoomInfoSetisMembersOnlyNative(IntPtr obj, Boolean isMembersOnly);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRoomInfoGetisPasswordProtectedNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern void VidyoRoomInfoSetisPasswordProtectedNative(IntPtr obj, Boolean isPasswordProtected);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRoomInfoGetisPublicNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern void VidyoRoomInfoSetisPublicNative(IntPtr obj, Boolean isPublic);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRoomInfoGetisRoleChangeAllowedNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern void VidyoRoomInfoSetisRoleChangeAllowedNative(IntPtr obj, Boolean isRoleChangeAllowed);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetlanguageNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRoomInfoSetlanguageNative(IntPtr obj, IntPtr language);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoRoomInfoGetmaxParticipantsNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRoomInfoSetmaxParticipantsNative(IntPtr obj, uint maxParticipants);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetmessageListNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRoomInfoSetmessageListNative(IntPtr obj, IntPtr messageList, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetmessageListArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRoomInfoFreemessageListArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetnameNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRoomInfoSetnameNative(IntPtr obj, IntPtr name);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern int VidyoRoomInfoGetnumUsersNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRoomInfoSetnumUsersNative(IntPtr obj, int numUsers);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetownerListNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRoomInfoSetownerListNative(IntPtr obj, IntPtr ownerList, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetownerListArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRoomInfoFreeownerListArrayNative(IntPtr obj, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern Room.RoomType VidyoRoomInfoGettypeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern void VidyoRoomInfoSettypeNative(IntPtr obj, Room.RoomType type);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetuserListNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRoomInfoSetuserListNative(IntPtr obj, IntPtr userList, int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRoomInfoGetuserListArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRoomInfoFreeuserListArrayNative(IntPtr obj, int size);

		public ulong creationTime;
		public String description;
		public String extension;
		public String id;
		public Boolean isFavorite;
		public Boolean isMembersOnly;
		public Boolean isPasswordProtected;
		public Boolean isPublic;
		public Boolean isRoleChangeAllowed;
		public String language;
		public uint maxParticipants;
		public List<ChatMessage> messageList;
		public String name;
		public int numUsers;
		public List<String> ownerList;
		public Room.RoomType type;
		public List<String> userList;
		public RoomInfo(IntPtr obj){
			objPtr = obj;

			List<ChatMessage> csMessageList = new List<ChatMessage>();
			int nMessageListSize = 0;
			IntPtr nMessageList = VidyoRoomInfoGetmessageListArrayNative(VidyoRoomInfoGetmessageListNative(objPtr), ref nMessageListSize);
			int nMessageListIndex = 0;
			while (nMessageListIndex < nMessageListSize) {
				ChatMessage csTmessageList = new ChatMessage(Marshal.ReadIntPtr(nMessageList + (nMessageListIndex * Marshal.SizeOf(nMessageList))));
				csMessageList.Add(csTmessageList);
				nMessageListIndex++;
			}

			List<String> csOwnerList = new List<String>();
			int nOwnerListSize = 0;
			IntPtr nOwnerList = VidyoRoomInfoGetownerListArrayNative(VidyoRoomInfoGetownerListNative(objPtr), ref nOwnerListSize);
			int nOwnerListIndex = 0;
			while (nOwnerListIndex < nOwnerListSize) {
				csOwnerList.Add((string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(Marshal.ReadIntPtr(nOwnerList + (nOwnerListIndex * Marshal.SizeOf(nOwnerList)))));
				nOwnerListIndex++;
			}

			List<String> csUserList = new List<String>();
			int nUserListSize = 0;
			IntPtr nUserList = VidyoRoomInfoGetuserListArrayNative(VidyoRoomInfoGetuserListNative(objPtr), ref nUserListSize);
			int nUserListIndex = 0;
			while (nUserListIndex < nUserListSize) {
				csUserList.Add((string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(Marshal.ReadIntPtr(nUserList + (nUserListIndex * Marshal.SizeOf(nUserList)))));
				nUserListIndex++;
			}

			creationTime = VidyoRoomInfoGetcreationTimeNative(objPtr);
			description = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoRoomInfoGetdescriptionNative(objPtr));
			extension = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoRoomInfoGetextensionNative(objPtr));
			id = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoRoomInfoGetidNative(objPtr));
			isFavorite = VidyoRoomInfoGetisFavoriteNative(objPtr);
			isMembersOnly = VidyoRoomInfoGetisMembersOnlyNative(objPtr);
			isPasswordProtected = VidyoRoomInfoGetisPasswordProtectedNative(objPtr);
			isPublic = VidyoRoomInfoGetisPublicNative(objPtr);
			isRoleChangeAllowed = VidyoRoomInfoGetisRoleChangeAllowedNative(objPtr);
			language = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoRoomInfoGetlanguageNative(objPtr));
			maxParticipants = VidyoRoomInfoGetmaxParticipantsNative(objPtr);
			messageList = csMessageList;
			name = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoRoomInfoGetnameNative(objPtr));
			numUsers = VidyoRoomInfoGetnumUsersNative(objPtr);
			ownerList = csOwnerList;
			type = VidyoRoomInfoGettypeNative(objPtr);
			userList = csUserList;
			VidyoRoomInfoFreeuserListArrayNative(nUserList, nUserListSize);
			VidyoRoomInfoFreeownerListArrayNative(nOwnerList, nOwnerListSize);
			VidyoRoomInfoFreemessageListArrayNative(nMessageList, nMessageListSize);
		}
	};
}
